name: "Allo Allo"
author: "Schalk Neethling"
description: "A welcome bot GitHub action for your project"
inputs:
  issueWelcome: # id of input
    description: "The greeting to display to the new contributor on issues."
    required: false
    default: "Welcome to the project! Thank you for your interest!"
  prWelcome: # id of input
    description: "The greeting to display to the new contributor on pull requests."
    required: false
    default: "Welcome to the project! Thank you for your contribution!"
  token:
    description: "Token for the repository. The default GITHUB_TOKEN can be used."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
