name: "Allo-Allo Welcome Bot"
author: "Mechanical Ink - Schalk Neethling"
branding:
  icon: 'award'
  color: 'green'
description: "A welcome bot GitHub action for your projects"
inputs:
  issueWelcome: # id of input
    description: "The greeting to display to the new contributor on issues."
    required: false
  prWelcome: # id of input
    description: "The greeting to display to the new contributor on pull requests."
    required: false
  prMerged: # id of input
    description: "The greeting to display to the contributor on pull requests that have been merged."
    required: false
  token:
    description: "Token for the repository. The default GITHUB_TOKEN can be used."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
